name: CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  changes:
    name: Determine Jobs
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      media-downloader: ${{ steps.filter.outputs.media-downloader }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - '.github/workflows/cd.yml'
              - 'frontend/**'
            backend:
              - '.github/workflows/cd.yml'
              - 'backend/**'
            media-downloader:
              - '.github/workflows/cd.yml'
              - 'media-downloader/**'

  frontend:
    name: Frontend CD
    runs-on: ubuntu-latest

    needs: [changes]
    if: ${{ needs.changes.outputs.frontend == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.11
        with:
          client-id: ${{ vars.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: '${{ vars.INFISICAL_PROJECT_SLUG }}'
          env-slug: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          secret-path: '/frontend'

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('/bun.lock') }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: frontend

      - name: Run linter
        run: bun run lint
        working-directory: frontend

      - name: Build project
        run: bun run build
        working-directory: frontend

      - name: Deploy Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'frontend/dist'
          skip_app_build: true

  backend:
    name: Backend CD
    runs-on: ubuntu-latest

    needs: [changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.11
        with:
          client-id: ${{ vars.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: '${{ vars.INFISICAL_PROJECT_SLUG }}'
          env-slug: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          secret-path: '/backend'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

      - name: Install dependencies
        run: go mod download
        working-directory: backend

      - name: Run linter
        run: test -z $(gofmt -l .)
        working-directory: backend

      - name: Build project
        run: go build application/server.go
        working-directory: backend

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: ghcr.io/tobias-kaerst-software/flipsen:latest

      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/tobias-kaerst-software/flipsen:latest

  media-downloader:
    name: Lint and build media downloader
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.outputs.media-downloader == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache-dependency-path: media-downloader/go.mod

      - name: Install dependencies
        run: go get .
        working-directory: media-downloader

      - name: Check code formatting
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
        working-directory: media-downloader

      - name: Check code style
        run: go vet
        working-directory: media-downloader

      - name: Build application
        run: go build -v -o app .
        working-directory: media-downloader

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: loggd-media-downloader-${{ runner.os }}
          path: media-downloader/app
          if-no-files-found: error
